services:
  usuario:
    restart: always
    container_name: usuario
    build:
      context: ./usuario
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbUsuario:5432/usuariodb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SERVER_PORT=8082
    ports:
      - '8083:8082'
    depends_on:
      - dbUsuario
    networks:
      - network_usuario
      - network_api_gateway

  dbUsuario:
    image: postgres:latest
    restart: always
    container_name: dbUsuario
    environment:
      POSTGRES_DB: usuariodb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5433:5432'
    networks:
      - network_usuario

  reserva:
    restart: always
    container_name: reserva
    build:
      context: ./reserva
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbReserva:5432/reservadb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SERVER_PORT=8082
    ports:
      - '8084:8082'
    depends_on:
      - dbReserva
    networks:
      - network_reservas
      - network_api_gateway

  dbReserva:
    image: postgres:latest
    restart: always
    container_name: dbReserva
    environment:
      POSTGRES_DB: reservadb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5434:5432'
    networks:
      - network_reservas

  sala:
    restart: always
    container_name: sala
    build:
      context: ./sala
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbSala:5432/saladb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SERVER_PORT=8082
    ports:
      - '8085:8082'
    depends_on:
      - dbSala
    networks:
      - network_salas
      - network_api_gateway

  dbSala:
    image: postgres:latest
    restart: always
    container_name: dbSala
    environment:
      POSTGRES_DB: saladb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5435:5432'
    networks:
      - network_salas

  adminer:
    container_name: adminerMicro
    restart: always
    image: adminer:latest
    ports:
      - '8089:8080'
    networks:
      - network_usuario
      - network_reservas
      - network_salas
    
  web:
    image: nginx:latest
    volumes:
      - ./application/src:/usr/share/nginx/html
    ports:
      - "3000:80"
    networks:
      - network_api_gateway

networks:
  network_usuario:
    driver: bridge
  network_reservas:
    driver: bridge
  network_salas:
    driver: bridge
  network_api_gateway:
    driver: bridge
